import {
  ProjectInfo,
  ScheduleActivity,
  ExecutionEvent,
  AuditLogRecord,
  InstitutionalMemoryRecord,
} from '../types/nexus';

export const mockProject: ProjectInfo = {
  id: 'PROJ-OIL-2026-DNPL',
  code: 'OIL-DNPL-04',
  name: 'Duliajan to Numaligarh Pipeline Augmentation & Booster Station',
  client: 'Oil India Limited (OIL)',
  location: 'Assam Sector (Line 24, Block C, Booster Station 2)',
  baselineVersion: 'Rev-04-Baseline-2026.08',
  totalActivities: 48,
  completedActivities: 28,
  delayedActivities: 3,
  overallProgressPct: 68.4,
};

export const initialActivities: ScheduleActivity[] = [
  {
    id: 'act-L5.2.14',
    wbsCode: 'L5.2.14',
    name: 'Line 24 Pipe Spool Erection & Flange Bolting',
    discipline: 'Piping',
    location: 'Line 24 / Block B',
    equipmentTag: 'P-14 Header Spool',
    plannedStart: '2026-09-10',
    plannedEnd: '2026-09-13',
    actualStart: '2026-09-10',
    actualEnd: null, // To be marked completed upon planner approval of EV-10492
    baselineDurationDays: 4,
    actualDurationDays: null,
    progressPct: 85,
    isCriticalPath: true,
    predecessorIds: ['act-L5.2.13'],
    status: 'IN_PROGRESS',
    varianceDays: 0,
    unitOfMeasure: 'Spools',
    plannedQuantity: 12,
    installedQuantity: 10,
  },
  {
    id: 'act-L5.2.15',
    wbsCode: 'L5.2.15',
    name: 'Line 24 Tie-in Joint Radiographic Testing (NDT)',
    discipline: 'HSE',
    location: 'Line 24 / Block B',
    equipmentTag: 'Joint J-24-01 to J-24-06',
    plannedStart: '2026-09-14',
    plannedEnd: '2026-09-16',
    actualStart: null,
    actualEnd: null,
    baselineDurationDays: 3,
    actualDurationDays: null,
    progressPct: 0,
    isCriticalPath: true,
    predecessorIds: ['act-L5.2.14'],
    status: 'NOT_STARTED',
    varianceDays: 0,
    unitOfMeasure: 'Joints',
    plannedQuantity: 6,
    installedQuantity: 0,
  },
  {
    id: 'act-L5.1.08',
    wbsCode: 'L5.1.08',
    name: 'Block C Compressor Foundation Concrete Pouring (M35 Grade)',
    discipline: 'Civil',
    location: 'Block C',
    equipmentTag: 'CMP-FND-03',
    plannedStart: '2026-09-12',
    plannedEnd: '2026-09-14',
    actualStart: '2026-09-13T10:00:00',
    actualEnd: null,
    baselineDurationDays: 2,
    actualDurationDays: null,
    progressPct: 40,
    isCriticalPath: false,
    predecessorIds: ['act-L5.1.07'],
    status: 'HALTED',
    varianceDays: 1,
    unitOfMeasure: 'm³',
    plannedQuantity: 65,
    installedQuantity: 26,
  },
  {
    id: 'act-L5.1.09',
    wbsCode: 'L5.1.09',
    name: 'Block C Foundation Wet Curing & De-shuttering',
    discipline: 'Civil',
    location: 'Block C',
    equipmentTag: 'CMP-FND-03',
    plannedStart: '2026-09-15',
    plannedEnd: '2026-09-22',
    actualStart: null,
    actualEnd: null,
    baselineDurationDays: 7,
    actualDurationDays: null,
    progressPct: 0,
    isCriticalPath: false,
    predecessorIds: ['act-L5.1.08'],
    status: 'NOT_STARTED',
    varianceDays: 1,
    unitOfMeasure: 'Days',
    plannedQuantity: 7,
    installedQuantity: 0,
  },
  {
    id: 'act-L5.3.02',
    wbsCode: 'L5.3.02',
    name: 'Pump P-14 Crude Booster Baseplate Precision Dial Alignment',
    discipline: 'Mechanical / Rotating',
    location: 'Pump Station 2',
    equipmentTag: 'P-14 Booster Unit',
    plannedStart: '2026-09-08',
    plannedEnd: '2026-09-11',
    actualStart: '2026-09-08',
    actualEnd: '2026-09-11',
    baselineDurationDays: 4,
    actualDurationDays: 4,
    progressPct: 100,
    isCriticalPath: true,
    predecessorIds: [],
    status: 'COMPLETED',
    varianceDays: 0,
    unitOfMeasure: 'Shafts',
    plannedQuantity: 1,
    installedQuantity: 1,
  },
  {
    id: 'act-L5.4.11',
    wbsCode: 'L5.4.11',
    name: 'Motor Control Center (MCC-02) 415V Busbar Insulation Meggering',
    discipline: 'Electrical',
    location: 'Substation 1',
    equipmentTag: 'MCC-02 Panel',
    plannedStart: '2026-09-09',
    plannedEnd: '2026-09-12',
    actualStart: '2026-09-09',
    actualEnd: '2026-09-13',
    baselineDurationDays: 3,
    actualDurationDays: 4,
    progressPct: 100,
    isCriticalPath: false,
    predecessorIds: [],
    status: 'COMPLETED',
    varianceDays: 1,
    unitOfMeasure: 'Feeders',
    plannedQuantity: 14,
    installedQuantity: 14,
  },
  {
    id: 'act-L5.5.06',
    wbsCode: 'L5.5.06',
    name: 'Pressure Transmitter PT-2401 Impulse Tubing & Loop Calibration',
    discipline: 'Instrumentation',
    location: 'Line 24 / Block B',
    equipmentTag: 'PT-2401',
    plannedStart: '2026-09-15',
    plannedEnd: '2026-09-17',
    actualStart: null,
    actualEnd: null,
    baselineDurationDays: 3,
    actualDurationDays: null,
    progressPct: 0,
    isCriticalPath: false,
    predecessorIds: ['act-L5.2.14'],
    status: 'NOT_STARTED',
    varianceDays: 0,
    unitOfMeasure: 'Loops',
    plannedQuantity: 2,
    installedQuantity: 0,
  },
  {
    id: 'act-L5.6.01',
    wbsCode: 'L5.6.01',
    name: 'Permit-to-Work (PTW) Hot Work Gas Testing & Scaffold Inspection',
    discipline: 'HSE',
    location: 'Line 24 / Block B',
    equipmentTag: 'Zone 1 Enclosure',
    plannedStart: '2026-09-10',
    plannedEnd: '2026-09-10',
    actualStart: '2026-09-10',
    actualEnd: '2026-09-10',
    baselineDurationDays: 1,
    actualDurationDays: 1,
    progressPct: 100,
    isCriticalPath: true,
    predecessorIds: [],
    status: 'COMPLETED',
    varianceDays: 0,
    unitOfMeasure: 'Permits',
    plannedQuantity: 1,
    installedQuantity: 1,
  },
];

export const initialEvents: ExecutionEvent[] = [
  {
    id: 'ev-10492',
    eventNumber: 'EV-10492',
    reporterId: 'SUP-017',
    reporterName: 'Supervisor R. Bora',
    reporterRole: 'Lead Piping Supervisor',
    rawInput: 'Line 24 pipe spool erection completed around 3 PM today.',
    inputMode: 'voice',
    audioDurationSeconds: 6,
    createdAt: '2026-09-13T15:10:00Z',

    eventType: 'completed',
    activityDescription: 'Pipe spool erection on Line 24',
    candidateLocation: 'Line 24',
    startTime: null, // explicit null
    endTime: '15:00',
    status: 'completed',
    quantity: 12,
    unit: 'spools',
    blocker: null, // explicit null
    expectedResumption: null, // explicit null
    evidenceReferences: ['Photo P-1827', 'Daily Report DR-0913'],
    notes: 'Flange torquing completed as per specification ASME B31.4.',

    matchingConfidence: 0.96,
    evidenceConfidence: 0.94,
    selectedActivityId: 'act-L5.2.14',
    governanceStatus: 'PENDING_REVIEW',

    candidateMatches: [
      {
        activityId: 'act-L5.2.14',
        wbsCode: 'L5.2.14',
        activityName: 'Line 24 Pipe Spool Erection & Flange Bolting',
        discipline: 'Piping',
        location: 'Line 24 / Block B',
        equipmentTag: 'P-14 Header Spool',
        overallConfidence: 0.96,
        scoreBreakdown: {
          semantic: 0.98,
          location: 0.95,
          discipline: 0.99,
          scheduleWindow: 0.94,
          equipmentMatch: 0.92,
        },
        rationale:
          'High lexical and semantic overlap with planned activity. Location Line 24 matches schedule baseline window (Sep 10-13).',
      },
      {
        activityId: 'act-L5.2.15',
        wbsCode: 'L5.2.15',
        activityName: 'Line 24 Tie-in Joint Radiographic Testing (NDT)',
        discipline: 'HSE',
        location: 'Line 24 / Block B',
        overallConfidence: 0.44,
        scoreBreakdown: {
          semantic: 0.41,
          location: 0.95,
          discipline: 0.2,
          scheduleWindow: 0.3,
          equipmentMatch: 0.1,
        },
        rationale:
          'Same location Line 24, but event refers to physical spool erection, not NDT inspection.',
      },
    ],

    evidenceList: [
      {
        id: 'evid-01',
        eventId: 'ev-10492',
        fileName: 'P-1827_Spool_Flange_Joint.jpg',
        fileType: 'photo',
        fileUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f8?w=800&auto=format&fit=crop&q=60',
        uploaderId: 'SUP-017',
        uploaderName: 'Supervisor R. Bora',
        timestamp: '2026-09-13T15:02:14Z',
        gpsCoordinates: {
          lat: 27.3482,
          lng: 95.3219,
          siteZone: 'Line 24 East Corridor (Zone A)',
          accuracyMeters: 3.2,
        },
        metadataValid: true,
        visualConsistencyScore: 0.94,
        notes: 'EXIF timestamp matches reported completion time within 5 mins.',
      },
      {
        id: 'evid-02',
        eventId: 'ev-10492',
        fileName: 'DR-0913_Daily_Log_Sheet.pdf',
        fileType: 'report_pdf',
        fileUrl: '',
        uploaderId: 'SUP-017',
        uploaderName: 'Supervisor R. Bora',
        timestamp: '2026-09-13T15:05:00Z',
        metadataValid: true,
        visualConsistencyScore: 0.91,
        notes: 'Signed by Shift Engineer. Mentions 12 spools aligned & torqued.',
      },
    ],
  },
  {
    id: 'ev-10493',
    eventNumber: 'EV-10493',
    reporterId: 'SUP-022',
    reporterName: 'Supervisor M. Kalita',
    reporterRole: 'Civil Works Supervisor',
    rawInput:
      'Concrete pouring for Block C started at 10. We stopped at 1 because the batching plant failed and we will resume tomorrow.',
    inputMode: 'voice',
    audioDurationSeconds: 9,
    createdAt: '2026-09-13T13:20:00Z',

    eventType: 'interrupted',
    activityDescription: 'Concrete pouring for Block C compressor foundation',
    candidateLocation: 'Block C',
    startTime: '10:00',
    endTime: '13:00',
    status: 'interrupted',
    quantity: 26,
    unit: 'm³',
    blocker: 'Batching plant motor drive breakdown (mechanical failure)',
    expectedResumption: '2026-09-14 08:00 AM',
    evidenceReferences: ['Plant Maintenance Incident Log #442'],
    notes: 'Cold joint management initiated. Retarder applied to edge.',

    matchingConfidence: 0.93,
    evidenceConfidence: 0.88,
    selectedActivityId: 'act-L5.1.08',
    governanceStatus: 'PENDING_REVIEW',

    candidateMatches: [
      {
        activityId: 'act-L5.1.08',
        wbsCode: 'L5.1.08',
        activityName: 'Block C Compressor Foundation Concrete Pouring (M35 Grade)',
        discipline: 'Civil',
        location: 'Block C',
        equipmentTag: 'CMP-FND-03',
        overallConfidence: 0.93,
        scoreBreakdown: {
          semantic: 0.96,
          location: 0.98,
          discipline: 0.97,
          scheduleWindow: 0.92,
          equipmentMatch: 0.85,
        },
        rationale:
          'Exact match for Block C concrete pouring in current active schedule window.',
      },
      {
        activityId: 'act-L5.1.09',
        wbsCode: 'L5.1.09',
        activityName: 'Block C Foundation Wet Curing & De-shuttering',
        discipline: 'Civil',
        location: 'Block C',
        overallConfidence: 0.38,
        scoreBreakdown: {
          semantic: 0.35,
          location: 0.98,
          discipline: 0.95,
          scheduleWindow: 0.2,
          equipmentMatch: 0.2,
        },
        rationale: 'Successor activity; cannot begin until pouring completes.',
      },
    ],

    evidenceList: [
      {
        id: 'evid-03',
        eventId: 'ev-10493',
        fileName: 'Batching_Plant_Alarm_Log.pdf',
        fileType: 'report_pdf',
        fileUrl: '',
        uploaderId: 'SUP-022',
        uploaderName: 'Supervisor M. Kalita',
        timestamp: '2026-09-13T13:15:20Z',
        metadataValid: true,
        visualConsistencyScore: 0.88,
        notes: 'Trip log verifies plant failure at 12:54 PM.',
      },
    ],
  },
  {
    id: 'ev-10491',
    eventNumber: 'EV-10491',
    reporterId: 'SUP-009',
    reporterName: 'Supervisor A. Goswami',
    reporterRole: 'Rotating Equipment Specialist',
    rawInput:
      'Pump P-14 booster alignment completed. Vibrations within ISO 10816 tolerance under 1.8 mm/s.',
    inputMode: 'text',
    createdAt: '2026-09-11T16:45:00Z',

    eventType: 'completed',
    activityDescription: 'Pump P-14 booster alignment',
    candidateLocation: 'Pump Station 2',
    startTime: '2026-09-08',
    endTime: '2026-09-11 16:30',
    status: 'completed',
    quantity: 1,
    unit: 'shaft',
    blocker: null,
    expectedResumption: null,
    evidenceReferences: ['Dial Indicator Report #DI-90', 'Photo P-1801'],
    notes: 'Laser alignment report verified by Lead Mechanical Engineer.',

    matchingConfidence: 0.98,
    evidenceConfidence: 0.96,
    selectedActivityId: 'act-L5.3.02',
    governanceStatus: 'APPROVED',
    reviewedBy: 'P. Sharma (Sr. Project Planner)',
    reviewedAt: '2026-09-11T17:30:00Z',
    plannerReviewNotes: 'Verified against alignment test certificate. Activity closed.',

    candidateMatches: [
      {
        activityId: 'act-L5.3.02',
        wbsCode: 'L5.3.02',
        activityName: 'Pump P-14 Crude Booster Baseplate Precision Dial Alignment',
        discipline: 'Mechanical / Rotating',
        location: 'Pump Station 2',
        equipmentTag: 'P-14 Booster Unit',
        overallConfidence: 0.98,
        scoreBreakdown: {
          semantic: 0.99,
          location: 0.96,
          discipline: 0.99,
          scheduleWindow: 0.98,
          equipmentMatch: 0.99,
        },
        rationale: 'Tag P-14 and alignment term exactly match L5.3.02.',
      },
    ],

    evidenceList: [
      {
        id: 'evid-04',
        eventId: 'ev-10491',
        fileName: 'P-1801_Dial_Gauge_Alignment.jpg',
        fileType: 'photo',
        fileUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=60',
        uploaderId: 'SUP-009',
        uploaderName: 'Supervisor A. Goswami',
        timestamp: '2026-09-11T16:35:12Z',
        metadataValid: true,
        visualConsistencyScore: 0.96,
        notes: 'Laser alignment readout clearly visible.',
      },
    ],
  },
];

export const initialAuditLogs: AuditLogRecord[] = [
  {
    id: 'audit-001',
    timestamp: '2026-09-11T17:30:00Z',
    actorId: 'PLN-003',
    actorName: 'P. Sharma',
    actorRole: 'Senior Project Planner',
    action: 'APPROVE_SCHEDULE_UPDATE',
    targetEntity: 'ScheduleActivity',
    entityId: 'act-L5.3.02',
    beforeState: {
      status: 'IN_PROGRESS',
      progressPct: 70,
      actualEnd: null,
    },
    afterState: {
      status: 'COMPLETED',
      progressPct: 100,
      actualEnd: '2026-09-11',
    },
    rationale: 'Event EV-10491 verified with dial test certificate and laser alignment photo.',
    evidenceHash: 'sha256:8f4c2e...b3a1',
  },
  {
    id: 'audit-002',
    timestamp: '2026-09-13T13:25:00Z',
    actorId: 'SYS-NEXUS',
    actorName: 'NEXUS Autonomous Engine',
    actorRole: 'System Pipeline',
    action: 'FLAG_SCHEDULE_INTERRUPTION',
    targetEntity: 'ScheduleActivity',
    entityId: 'act-L5.1.08',
    beforeState: {
      status: 'IN_PROGRESS',
      varianceDays: 0,
    },
    afterState: {
      status: 'HALTED',
      varianceDays: 1,
      blocker: 'Batching plant breakdown',
    },
    rationale: 'Derived from Field Event EV-10493; queued for planner confirmation.',
    evidenceHash: 'sha256:77d1a2...99f0',
  },
  {
    id: 'audit-003',
    timestamp: '2026-09-13T15:12:00Z',
    actorId: 'SYS-NEXUS',
    actorName: 'NEXUS NLP Pipeline',
    actorRole: 'System Extraction',
    action: 'EXTRACT_EXECUTION_EVENT',
    targetEntity: 'ExecutionEvent',
    entityId: 'ev-10492',
    beforeState: null,
    afterState: {
      rawInput: 'Line 24 pipe spool erection completed around 3 PM today.',
      extractedConfidence: 0.96,
      candidateActivity: 'L5.2.14',
    },
    rationale: 'Supervisor voice recording parsed; candidate matches computed via pgvector.',
    evidenceHash: 'sha256:5512b9...11ac',
  },
];

export const mockInstitutionalMemory: InstitutionalMemoryRecord[] = [
  {
    id: 'mem-01',
    title: 'DNPL Phase 1: Line 18 Pipe Spool Alignment & Torquing Delay',
    projectCode: 'OIL-DNPL-01',
    discipline: 'Piping',
    date: '2024-11-14',
    summary:
      'Spool erection faced 4-day critical path delay due to bolt grade mismatch and monsoonal access route slippage.',
    rootCause:
      'Fabrication vendor delivered ASTM A193 B7 bolts without 3.1 Mill Test Certificates; site QA quarantined lot until third-party lab verification.',
    resolution:
      'Pre-shipment verification mandate instituted for sub-vendors; buffer stock of verified studs and spiral wound gaskets established at central warehouse.',
    relevanceScore: 0.94,
    sourceEventRef: 'HIST-EV-4819',
    matchedKeywords: ['pipe spool erection', 'delays', 'causes', 'Line 24', 'Piping'],
  },
  {
    id: 'mem-02',
    title: 'Barauni Feeder Pipeline: High-Pressure Tie-In Radiography Backlog',
    projectCode: 'OIL-BFP-03',
    discipline: 'HSE',
    date: '2025-03-22',
    summary:
      'NDT radiography backlog delayed hydrostatic test readiness by 6 calendar days.',
    rootCause:
      'Atomic Energy Regulatory Board (AERB) radioactive source storage enclosure permits delayed; night radiography restricted.',
    resolution:
      'Switched to Phased Array Ultrasonic Testing (PAUT) for 80% of girth welds, eliminating darkroom radiography exclusion zones during daytime shifts.',
    relevanceScore: 0.89,
    sourceEventRef: 'HIST-EV-6210',
    matchedKeywords: ['pipe spool', 'radiographic testing', 'NDT', 'tie-in', 'delays'],
  },
  {
    id: 'mem-03',
    title: 'Compressor Station 3: Batching Plant Moisture Compensation Issue',
    projectCode: 'OIL-CS-02',
    discipline: 'Civil',
    date: '2025-07-09',
    summary:
      'Compressor foundation pour halted midway due to sudden aggregate moisture surge causing mix rejection at chute.',
    rootCause:
      'Heavy unforecasted rainfall saturated sand bunkers; batching plant auto-moisture probe calibration had drifted by +4.2%.',
    resolution:
      'Installed covered aggregate shed and instituted manual moisture burn-off verification every 2 hours during continuous pours.',
    relevanceScore: 0.86,
    sourceEventRef: 'HIST-EV-5541',
    matchedKeywords: ['concrete pouring', 'batching plant failure', 'interrupted', 'Civil'],
  },
  {
    id: 'mem-04',
    title: 'Numaligarh Terminus: Booster Pump P-12 Shaft Runout Rectification',
    projectCode: 'OIL-NT-01',
    discipline: 'Mechanical / Rotating',
    date: '2024-05-18',
    summary:
      'Booster pump alignment exceeded 0.05mm radial runout during cold coupling.',
    rootCause:
      'Piping strain on pump suction flange caused soft-foot deformation on drive-end skid.',
    resolution:
      'Loosened piping spring hangers, re-torqued flange with laser dial monitoring, eliminated piping nozzle strain.',
    relevanceScore: 0.78,
    sourceEventRef: 'HIST-EV-3904',
    matchedKeywords: ['booster pump', 'alignment', 'vibration', 'Mechanical'],
  },
];
